### ISSUE TITLE
Content failed to load.

### ISSUE THREAD

**Issue by Worldgate** [miragedmuk/ASV#10]
Windows 10, v5.0.0.9, ASE, getting this error and refuses to do anything.

"Content failed to load."  Snagged the log file in case its helpful.  The map loads fine with the server, i can build and tame and such, but trying to load it into ASGV and i get that. :/  Any helpful pointers would be great.

```
2023-12-29 10:59:08.9400|INFO|Reading game save data...
2023-12-29 10:59:18.7929|ERROR|LoadSaveGame failedSystem.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at SavegameToolkit.ArkArchive.readNameFromTable() in C:\Dev\ASV_New\ASVPack\ArkSavegameToolkit\SavegameToolkit\ArkArchive.cs:line 206
   at SavegameToolkit.Propertys.PropertyRegistry.ReadBinary(ArkArchive archive) in C:\Dev\ASV_New\ASVPack\ArkSavegameToolkit\SavegameToolkit\Propertys\PropertyRegistry.cs:line 70
   at SavegameToolkit.GameObject.LoadProperties(ArkArchive archive, GameObject next, Int64 propertiesBlockOffset) in C:\Dev\ASV_New\ASVPack\ArkSavegameToolkit\SavegameToolkit\GameObject.cs:line 165
   at SavegameToolkit.ArkSavegame.readBinaryObjectProperties(ArkArchive archive, ReadingOptions options) in C:\Dev\ASV_New\ASVPack\ArkSavegameToolkit\SavegameToolkit\ArkSavegame.cs:line 850
   at SavegameToolkit.ArkSavegame.ReadBinary(ArkArchive archive, ReadingOptions options) in C:\Dev\ASV_New\ASVPack\ArkSavegameToolkit\SavegameToolkit\ArkSavegame.cs:line 628
   at ASVPack.Models.ContentContainer.LoadArkEvolvedData(String saveFilename) in C:\Dev\ASV_New\ASVPack\ASVPack\Models\ContentContainer.cs:line 480
   at ASVPack.Models.ContentContainer.LoadSaveGame(String saveFilename, String localProfileFilename, String clusterFolder, Int32 profileDayCountLimit) in C:\Dev\ASV_New\ASVPack\ASVPack\Models\ContentContainer.cs:line 229    at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at SavegameToolkit.ArkArchive.readNameFromTable() in C:\Dev\ASV_New\ASVPack\ArkSavegameToolkit\SavegameToolkit\ArkArchive.cs:line 206
   at SavegameToolkit.Propertys.PropertyRegistry.ReadBinary(ArkArchive archive) in C:\Dev\ASV_New\ASVPack\ArkSavegameToolkit\SavegameToolkit\Propertys\PropertyRegistry.cs:line 70
   at SavegameToolkit.GameObject.LoadProperties(ArkArchive archive, GameObject next, Int64 propertiesBlockOffset) in C:\Dev\ASV_New\ASVPack\ArkSavegameToolkit\SavegameToolkit\GameObject.cs:line 165
   at SavegameToolkit.ArkSavegame.readBinaryObjectProperties(ArkArchive archive, ReadingOptions options) in C:\Dev\ASV_New\ASVPack\ArkSavegameToolkit\SavegameToolkit\ArkSavegame.cs:line 850
   at SavegameToolkit.ArkSavegame.ReadBinary(ArkArchive archive, ReadingOptions options) in C:\Dev\ASV_New\ASVPack\ArkSavegameToolkit\SavegameToolkit\ArkSavegame.cs:line 628
   at ASVPack.Models.ContentContainer.LoadArkEvolvedData(String saveFilename) in C:\Dev\ASV_New\ASVPack\ASVPack\Models\ContentContainer.cs:line 480
   at ASVPack.Models.ContentContainer.LoadSaveGame(String saveFilename, String localProfileFilename, String clusterFolder, Int32 profileDayCountLimit) in C:\Dev\ASV_New\ASVPack\ASVPack\Models\ContentContainer.cs:line 229

```

**Comment by miragedmuk** [comment]
Don't be so keen and let the other guinnea pigs test it first :)

Latest release fixes this.

**Comment by Worldgate** [comment]
https://drive.google.com/file/d/1mT5GX_R8jD1EmElsg5etSXMOZsQl9_cb/view?usp=drive_link

**Comment by miragedmuk** [comment]
Ironically.. download failed to load :) Access Denied.  Have sent you an access request.

**Comment by Worldgate** [comment]
https://drive.google.com/file/d/1mT5GX_R8jD1EmElsg5etSXMOZsQl9_cb/view?usp=sharing

i set it to anyone with link

**Comment by Worldgate** [comment]
let me know if that works
 otherwise i can throw it on my ftp server locally

**Comment by miragedmuk** [comment]
Yeah that worked.  Got the backup and found the issue.

Something to do with "CCA Custom Data" - maybe a mod? Either way I've amended the code so it continues to read known properties and only skips out if it attempts one it doesn't instead of failing to load.

**Comment by Worldgate** [comment]
Yea i tried removing mods to get it to read, it was suddenly no longer reading no matter how many times i reloaded it.

Just by chance do you know how to just extract the 'pack' data from a save so i can just dump the data and import it via the save pack?
